/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on 18-oct-2009, 16:12:41
 */

package virtual_control_room;

import ServiceDDS.Peer;
import ServiceDDS.service.RemoteServiceInstance;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JTabbedPane;
import virtual_control_room.view.View;
import virtual_control_room.view.evolutionline.EvolutionLineChartView;
import virtual_control_room.view.instant_table.InstantTableView;
import virtual_control_room.view.vial.VialView;

/**
 *
 * @author JA Dianes
 */
public class GUI extends javax.swing.JFrame {

    VCR vcr;

    List<View> viewList = new LinkedList();
    InstantTableView itv1;
    VialView tv1;
    EvolutionLineChartView elcv1;

    InstantTableView itv2;
    VialView tv2;
    EvolutionLineChartView elcv2;

    InstantTableView itv3;
    VialView tv3;
    EvolutionLineChartView elcv3;

    JTabbedPane jTabbedPaneViews;

    Peer myPeer;
    RemoteServiceInstance serialOutputService;

    ParticipantMotesJFrame participants = new ParticipantMotesJFrame();

    /** Creates new form GUI */
    public GUI() {
        SplashDemo sd = new SplashDemo();
        
        initComponents();
        this.jTabbedPaneViews = this.jTabbedPane1;

//        itv1 = (InstantTableView) this.jTable11;
//        tv1 = (ThermometerView) this.jThermometerPanel11;
//        elcv1 = (EvolutionLineChartView) this.jEvolutionPanel11;
//
//        itv2 = (InstantTableView) this.jTable21;
//        tv2 = (ThermometerView) this.jThermometerPanel21;
//        elcv2 = (EvolutionLineChartView) this.jEvolutionPanel21;
//
//        itv3 = (InstantTableView) this.jTable31;
//        tv3 = (ThermometerView) this.jThermometerPanel31;
//        elcv3 = (EvolutionLineChartView) this.jEvolutionPanel31;

        vcr = new VCR(this);
// ALAMAR SAMPLE USE        vcr.newAlarm(new TemperatureThresholdAlarm(vcr.myPeer, 23.0, this, vcr.ras));
 //       SquidBeeDataFilter sbDataFilter = new SquidBeeDataFilter();

//        this.myPeer = new Peer("GUI", new Group("SERIAL"));
//        this.serialOutputService = this.myPeer.lookForService(
//                new ServiceContractTemplate("SerialOutputService",this.myPeer.getName()),
//                new QoSParameters());
    }

    public void showAlarmMessage(String message) {
        this.jTextAreaAlarms.setText(message);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAlarms = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuView = new javax.swing.JMenu();
        jMenuItemNewView = new javax.swing.JMenuItem();
        jMenuItemWebView = new javax.swing.JMenuItem();
        jMenuItemParticipantsView = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Habitat VCR");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextAreaAlarms.setColumns(20);
        jTextAreaAlarms.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAlarms);

        jMenuFile.setText("File");
        jMenuBar1.add(jMenuFile);

        jMenuView.setText("View");

        jMenuItemNewView.setText("Create view panel...");
        jMenuItemNewView.setEnabled(false);
        jMenuItemNewView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewViewActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemNewView);

        jMenuItemWebView.setText("Create Web view panel...");
        jMenuItemWebView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWebViewActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemWebView);

        jMenuItemParticipantsView.setText("Show participants view");
        jMenuItemParticipantsView.setEnabled(false);
        jMenuItemParticipantsView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemParticipantsViewActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemParticipantsView);

        jMenuBar1.add(jMenuView);

        jMenu1.setText("Connect");

        jMenuItem2.setText("Connect to Habitat (LAN)");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton1))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        vcr.command("HELLO");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemNewViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewViewActionPerformed
        NewViewJFrame newView = new NewViewJFrame(this);
        newView.setVisible(true);
    }//GEN-LAST:event_jMenuItemNewViewActionPerformed

    private void jMenuItemParticipantsViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemParticipantsViewActionPerformed
        this.vcr.beholder.showParticipansView();
    }//GEN-LAST:event_jMenuItemParticipantsViewActionPerformed

    private void jMenuItemWebViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWebViewActionPerformed
        NewWebViewJFrame newWebView = new NewWebViewJFrame(this);
        newWebView.setVisible(true);
    }//GEN-LAST:event_jMenuItemWebViewActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            vcr.connectToHabitat();
            this.jMenuItemNewView.setEnabled(true);
            this.jMenuItemParticipantsView.setEnabled(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemNewView;
    private javax.swing.JMenuItem jMenuItemParticipantsView;
    private javax.swing.JMenuItem jMenuItemWebView;
    private javax.swing.JMenu jMenuView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaAlarms;
    // End of variables declaration//GEN-END:variables


//    public void showSample(Sample s) {
//    }

    public void addView(View v) {
        this.viewList.add(v);
    }
}
