/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewViewJFrame.java
 *
 * Created on 30-ene-2010, 19:17:40
 */

package virtual_control_room;

import ServiceDDS.exception.ImpossibleToCreateDDSTopic;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import virtual_control_room.view.evolutionline.EvolutionLineChartView;
import virtual_control_room.view.instant_table.InstantTableViewSDDS;
import virtual_control_room.view.vial.VialViewSDDS;

/**
 *
 * @author JA Dianes
 */
public class NewViewJFrame extends javax.swing.JFrame {
    private String variableName;
    private String moteID;
    private GUI gui;

    /** Creates new form NewViewJFrame */
    public NewViewJFrame(GUI gui) {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.gui = gui;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelData = new javax.swing.JPanel();
        jPanelViewType = new javax.swing.JPanel();
        jComboBoxViewType = new javax.swing.JComboBox();
        jLabelViewType = new javax.swing.JLabel();
        jPanelVariable = new javax.swing.JPanel();
        jLabelVariable = new javax.swing.JLabel();
        jTextFieldVariable = new javax.swing.JTextField();
        jPanelMoteID = new javax.swing.JPanel();
        jLabelMoteID = new javax.swing.JLabel();
        jTextFieldMoteID = new javax.swing.JTextField();
        jPanelControl = new javax.swing.JPanel();
        jButtonConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New View Dialog");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jComboBoxViewType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Instant Table", "Vial", "Evolution Chart" }));
        jComboBoxViewType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxViewTypeActionPerformed(evt);
            }
        });

        jLabelViewType.setText("View type");

        javax.swing.GroupLayout jPanelViewTypeLayout = new javax.swing.GroupLayout(jPanelViewType);
        jPanelViewType.setLayout(jPanelViewTypeLayout);
        jPanelViewTypeLayout.setHorizontalGroup(
            jPanelViewTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelViewType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jComboBoxViewType, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelViewTypeLayout.setVerticalGroup(
            jPanelViewTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelViewTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxViewType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelViewType))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelVariable.setText("Variable name");

        jTextFieldVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVariableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVariableLayout = new javax.swing.GroupLayout(jPanelVariable);
        jPanelVariable.setLayout(jPanelVariableLayout);
        jPanelVariableLayout.setHorizontalGroup(
            jPanelVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVariableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVariable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jTextFieldVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelVariableLayout.setVerticalGroup(
            jPanelVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVariableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVariable)
                    .addComponent(jTextFieldVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelMoteID.setText("Mote ID");

        jTextFieldMoteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMoteIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMoteIDLayout = new javax.swing.GroupLayout(jPanelMoteID);
        jPanelMoteID.setLayout(jPanelMoteIDLayout);
        jPanelMoteIDLayout.setHorizontalGroup(
            jPanelMoteIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoteIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMoteID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jTextFieldMoteID, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelMoteIDLayout.setVerticalGroup(
            jPanelMoteIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoteIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMoteIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMoteID)
                    .addComponent(jTextFieldMoteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonConfirm.setText("Create");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelControlLayout = new javax.swing.GroupLayout(jPanelControl);
        jPanelControl.setLayout(jPanelControlLayout);
        jPanelControlLayout.setHorizontalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jButtonConfirm)
                .addContainerGap())
        );
        jPanelControlLayout.setVerticalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDataLayout = new javax.swing.GroupLayout(jPanelData);
        jPanelData.setLayout(jPanelDataLayout);
        jPanelDataLayout.setHorizontalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelViewType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMoteID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelDataLayout.setVerticalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addComponent(jPanelViewType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMoteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        switch (this.jComboBoxViewType.getSelectedIndex()) {
            case 0:
                this.newTable();
                break;
            case 1:
                this.newVial();
                break;
            case 2:
                this.newEvolutionChart();
                break;
        }
}//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jComboBoxViewTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxViewTypeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxViewTypeActionPerformed

    private void jTextFieldVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVariableActionPerformed
        this.variableName = this.jTextFieldVariable.getText();
    }//GEN-LAST:event_jTextFieldVariableActionPerformed

    private void jTextFieldMoteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMoteIDActionPerformed
        this.moteID = this.jTextFieldMoteID.getText();
    }//GEN-LAST:event_jTextFieldMoteIDActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewViewJFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JComboBox jComboBoxViewType;
    private javax.swing.JLabel jLabelMoteID;
    private javax.swing.JLabel jLabelVariable;
    private javax.swing.JLabel jLabelViewType;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JPanel jPanelMoteID;
    private javax.swing.JPanel jPanelVariable;
    private javax.swing.JPanel jPanelViewType;
    private javax.swing.JTextField jTextFieldMoteID;
    private javax.swing.JTextField jTextFieldVariable;
    // End of variables declaration//GEN-END:variables

    private void newEvolutionChart() {
        EvolutionLineChartView ev =
                new virtual_control_room.view.evolutionline.EvolutionLineChartViewSDDS(
                        this.jTextFieldVariable.getText(),
                        new Integer(this.jTextFieldMoteID.getText()).intValue(),
                        gui.vcr.myPeer,
                        true);
        ViewJFrame newFrame = new ViewJFrame();
        newFrame.setVisible(true);
        newFrame.setTitle(this.jTextFieldVariable.getText()+" Evolution Line Chart");
        newFrame.pane.add(ev);


    }

    private void newTable() {
        InstantTableViewSDDS itv = new InstantTableViewSDDS(gui.vcr.myPeer,new Integer(this.jTextFieldMoteID.getText()).intValue());
        JFrame newFrame = new JFrame();
        newFrame.setTitle(this.jTextFieldVariable.getText()+" Instant Table");
        newFrame.setVisible(true);
        newFrame.add(itv);
        newFrame.pack();
        newFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    private void newVial() {
        try {
            VialViewSDDS tv = new virtual_control_room.view.vial.VialViewSDDS(gui.vcr.myPeer, new Integer(this.jTextFieldMoteID.getText()).intValue(), this.jTextFieldVariable.getText(), 100, 100, 20.0);
            ViewJFrame newFrame = new ViewJFrame();
            newFrame.setTitle(this.jTextFieldVariable.getText() + " Thermometer");
            newFrame.setVisible(true);
            newFrame.pane.add(tv);
        } catch (ImpossibleToCreateDDSTopic ex) {
            Logger.getLogger(NewViewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
